### ISSUE TITLE
Website ค้าง

### ISSUE THREAD

**Issue by esp32cam** [learnalgorithmdotcom/7days-algorithm-fundamentals#13]
คือผมทำโจทย์บน web แล้วพอเกิด infinity loop แล้วมันค้างต้องรีหน้า web ใหม่ ตลอดเลยคับ

**Comment by chunrapeepat** [comment]
อันนี้แก้ยากนิดนึงครับ เพราะโค้ดที่ส่งมาจะ execute บน browser 

คิดว่าใช้ [Replit](https://replit.com/new/python3)  หรือเขียนโค้ดในเครื่องตัวเองก่อนแล้วค่อยก็อปมา submit บนเว็บช่วยได้ครับ
