### ISSUE TITLE
ผมกด submit ไปแต่มันไม่ submit ให้แล้วขึ้น error แบบนี้แปลว่าอะไรเหรอครับ

### ISSUE THREAD

**Issue by dragonnon2** [learnalgorithmdotcom/7days-algorithm-fundamentals#17]
![image](https://github.com/user-attachments/assets/8c971923-89a4-42fc-8633-ef295962531b)

ลองเสริซ google ดูแต่อ่านแล้วไม่เจออันที่เข้าใจน่ะครับ

**Comment by chunrapeepat** [comment]
ขอบคุณที่แจ้งครับ เป็น error ของเว็บเองครับ ไม่ได้เกี่ยวกับโค้ดที่ใส่เข้ามา ตอนนี้แก้ไขเรียบร้อยแล้วนะครับ รบกวนลองอีกรอบครับ
