### ISSUE TITLE
ทำยังไงถึงจะผ่านเข้าสู่เนื้อหาของวันถัดไปครับ

### ISSUE THREAD

**Issue by krdsxllntZ** [learnalgorithmdotcom/7days-algorithm-fundamentals#18]
ผมติดอยู่วันที่0มา3วันแล้วครับ คอมเม้นท์แล้ว ทำแบบฝึกหัดแล้ว ตอนแรกนึกว่ามันจะอัปเดตให้ผ่านเองหลังจากทำ2สิ่งนี้ ตอนนี้ยังเข้าเรียนเนื้อหาของคอร์ส1ไม่ได้เลยครับ

**Comment by chunrapeepat** [comment]
@krdsxllntZ รบกวนส่ง email ที่ใช้ login เข้าสู่ระบบเข้ามาใน [facebook page](https://www.facebook.com/learnalgorithm) ได้ไหมครับ

**Comment by ultimagz** [comment]
@chunrapeepat ถามด้วยครับ บทที่ 7 มาวันไหนเหรอครับ กลัวติดงานทำไม่ทัน claim cert :joy:

**Comment by chunrapeepat** [comment]
@ultimagz เปิดเนื้อหา day 7 - dynamic programming ให้แล้วครับผม
