### ISSUE TITLE
สวัสดีค่ะ ชื่อแอ็นค่ะ 

### ISSUE THREAD

**Issue by jjjaoant** [learnalgorithmdotcom/7days-algorithm-fundamentals#20]
ตอนนี้เรียนComputer Engineering ปี2อยู่ค่ะ สิ่งที่คาดหวังคือการเข้าใจAlgorithmค่ะ เพราะเรียนกับอจ ไม่ค่อยเก็ทเลยหาคอร์สข้างนอกเรียนเพิ่มค่ะ ช่วงนี้ไม่ได้สนใจอะไรเป็นพิเศษค่ะ อยู่ในช่วงหมดไฟกำลังหาอะไรเติมไ

**Comment by chunrapeepat** [comment]
หวังว่าคอร์สนี้จะช่วยให้เข้าใจ (+ เติมไฟ) ได้ไม่มากก็น้อยนะครับ ลุยครับ 🔥🔥
